brand: PHASICA
support_email: help.phasica@outlook.com
legal_email: yaenlenn@outlook.com
app_store_url: "https://testflight.apple.com/join/1Jw48ZEZ"
publication_num: "PUBLICATION / 001"
copyright_text: "© PHASICA"
default_locale: en
locales:
  - en
  - zh-CN
  - zh-TW
  - zh-HK
  - de
